<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Brimo_model extends CI_Model
{

    public $table = 'brimo';
    public $id = 'id';
    public $order = 'DESC';
    

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($pn = NULL, $pn1 = NULL) {
        $this->db->like('id', $pn);
	    $this->db->or_like('pn', $pn);
	    $this->db->or_like('tgl', $pn);
	    $this->db->or_like('norek', $pn);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function total_rows1($pn = NULL, $pn1 = NULL) {
        $this->db->or_like('pn', $pn);
        $this->db->where('pn', $pn1);
	    $this->db->or_like('tgl', $pn);
	    $this->db->where('pn', $pn1);
        $this->db->or_like('norek', $pn);
        $this->db->where('pn', $pn1);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }
  

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $pn = NULL, $pn1 = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->or_like('pn', $pn);
        $this->db->where('pn', $pn1);
	    $this->db->or_like('tgl', $pn);
	    $this->db->where('pn', $pn1);
        $this->db->or_like('norek', $pn);
        $this->db->where('pn', $pn1);
	    $this->db->from($this->table);
	    $this->db->where('pn', $pn1);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function get_limit_data1($limit, $start = 0, $pn = NULL, $pn1 = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $pn);
	    $this->db->or_like('pn', $pn);
	    $this->db->or_like('tgl', $pn);
	    $this->db->or_like('norek', $pn);
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Brimo_model.php */
/* Location: ./application/models/Brimo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-18 17:44:23 */
/* http://harviacode.com */