<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Qris_model extends CI_Model
{

    public $table = 'qris';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
       
        
        $this->db->select('*');
        $this->db->from('mantri');
        $this->db->join('qris','mantri.pn = qris.pn');      
        $this->db->join('account','mantri.branch = account.branch');
        
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('$this->table')->row();
    }
    
    function total_rows($pn = NULL) {
        // $this->db->like('id', $pn);
	    // $this->db->or_like('pn', $pn);
	    // $this->db->or_like('mid', $pn);
	    // $this->db->or_like('nama_merchant', $pn);
        // $this->db->or_like('norek', $pn);
        // $this->db->or_like('foto', $pn);
	    // $this->db->from('qris');
        $this->db->select('*');
        $this->db->from('mantri');
        $this->db->join('qris','mantri.pn = qris.pn');      
        $this->db->join('account','mantri.branch = account.branch');
        return $this->db->count_all_results();
    }

    function total_rows1($pn = NULL, $pn1 = NULL) {
        // $this->db->like('id', $pn);
	    // $this->db->or_like('pn',$pn,"match");
        // $this->db->where('pn', $pn1);
	    // $this->db->or_like('tgl', $pn);
        // $this->db->or_like('nama_qris',$pn,"match");
        // $this->db->where('pn', $pn1);
        // $this->db->or_like('norek', $pn,"match");
        // $this->db->where('pn', $pn1);
        // $this->db->or_like('hp', $pn,"match");
        $this->db->select('*');
        $this->db->from('mantri');
        $this->db->join('qris','mantri.pn = qris.pn');      
        $this->db->join('account','mantri.branch = account.branch');
        $this->db->where('pn', $pn1);
	    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

     // get data with limit and search
     function get_limit_data($limit, $start = 0, $pn = NULL, $pn1 = NULL) {
        // $this->db->order_by($this->id, $this->order);
	    // $this->db->or_like('pn',$pn,"match");
        // $this->db->where('pn', $pn1);
	    // $this->db->or_like('tgl', $pn);
        // $this->db->or_like('nama_qris',$pn,"match");
        // $this->db->where('pn', $pn1);
        // $this->db->or_like('norek', $pn,"match");
        // $this->db->where('pn', $pn1);
        // $this->db->or_like('hp', $pn,"match");
        // $this->db->where('pn', $pn1);
     
	    // $this->db->limit($limit, $start);
        // return $this->db->get($this->table)->result();
        $this->db->select('*');
        $this->db->from('mantri');
        $this->db->join('qris','mantri.pn = qris.pn');      
        $this->db->join('account','mantri.branch = account.branch');
        
        $query = $this->db->get();
        return $query;
    }
    // get data with limit and search
    function get_limit_data1($limit, $start = 0, $pn = NULL, $pn1 = NULL) {
        // $this->db->order_by($this->id, $this->order);
        // $this->db->like('id', $pn);
	    // $this->db->or_like('pn', $pn);
	    // $this->db->or_like('mid', $pn);
	    // $this->db->or_like('nama_merchant', $pn);
        // $this->db->or_like('norek', $pn);
        // $this->db->or_like('foto', $pn);
	    // $this->db->limit($limit, $start);
        // return $this->db->get($this->table)->result();

        $this->db->select('*');
        $this->db->from('mantri');
        $this->db->join('qris','mantri.pn = qris.pn');      
        $this->db->join('account','mantri.branch = account.branch');
        
        $query = $this->db->get();
        return $query;
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Qris_model.php */
/* Location: ./application/models/Qris_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-01-18 17:35:10 */
/* http://harviacode.com */
